### ISSUE TITLE
The url pointing to sample data is not working

### ISSUE THREAD

**Issue by edd34** [rosshochwert/arbitrage#4]
This url is not working : http://fx.priceonomics.com/v1/rates/?q=1

**Comment by rosshochwert** [comment]
The puzzle is no longer offered by priceonomics :( You can view the old data on the wayback machine [here](https://web.archive.org/web/20150323234057/http://fx.priceonomics.com/v1/rates/). It's static, unlike the original puzzle, but could be used for testing!
